### ISSUE TITLE
Error when large number of dice entered (>500?)

### ISSUE THREAD

**Issue by cSquall** [shanel/roller#11]
This error message comes up when a large number of dice are entered:

could not create new dice: API error 1 (datastore_v3: BAD_REQUEST): cannot write more than 500 entities in a single call

That's not critical, because if you backpage, any dice you had previously are still there.

**Comment by shanel** [comment]
Technically this is now fixed: no single roll can have a total number of entries greater than 500. Whichever types of rolls would have sent it over are just quietly skipped. This shouldn't be a huge issue: the user will see (assuming their screen even shows all the dice) that some classes are absent.

I wonder though if we shouldn't just limit the total to something reasonable like 50 or 100.
