### ISSUE TITLE
Each "submit" on cards is pulling from a separate deck.

### ISSUE THREAD

**Issue by bromidic** [shanel/roller#38]
This can be seen from a couple of different test cases. 
1) by submitting multiple times for small number of cards after each other you will eventually get repeats.
![image](https://user-images.githubusercontent.com/803899/29224936-364fadde-7e81-11e7-9721-594ec0b56901.png)
2) if you submit a number of cards greater than 52, you just get the whole deck (52 cards).
3) if you submit multiple times greater than 52, you just get multiple decks.
![image](https://user-images.githubusercontent.com/803899/29225145-f9a3a042-7e81-11e7-8a95-991f4a0d7f14.png)

**Comment by shanel** [comment]
Lovely... Yeah - looks like I am not actually saving the deck after it is being dealt from... Will fix this tonight hopefully.

**Comment by bromidic** [comment]
This may still be an issue.
If you submit a number larger than the remaining cards, you get all the remaining cards. (this is fine), but if you submit for more cards when there are no remaining cards you start drawing from a new deck.
