### ISSUE TITLE
Support custom decks.

### ISSUE THREAD

**Issue by shanel** [shanel/roller#41]
Maybe have them put in a csv or json or something and it creates a deck? Maybe accept pull requests for it. Its really just a bunch of pointers to images...

**Comment by shanel** [comment]
Could this also be an easy way to do something like the Crater for The Clay That Woke? (ie have the GM put in the deck contents as needed?)

**Comment by shanel** [comment]
Allow for custom names and multiple "decks?"

**Comment by shanel** [comment]
Still to do:

Dialog for creating custom sets (https://jqueryui.com/dialog/#modal-form)
Dialog for drawing from custom sets
making sure images are sized appropriately (css?)

**Comment by thorsten-panknin** [comment]
Hi Shane,

I added the example Tarot card set you linked from in your G+ post. Where do I find the button to draw from that set? Entering a number into the "cards" input field draws normal playing cards.

Cheers

**Comment by shanel** [comment]
Right next to the Add set button there should be two new buttons likely
named "Pull from Tarot" and "Randomize Tarot discards" - you'd click the
former.
