### ISSUE TITLE
How securely are images stored?

### ISSUE THREAD

**Issue by thorsten-panknin** [shanel/roller#50]
Hi,

I'm asking, because I'd like to approach a German game designer who created an rpg from cards. It's a bit like tarot.

Before I ask her about it, I'd like to make sure images would be securely stored and not accessible outside a game room that I set up.

Cheers,

Thorsten

**Comment by shanel** [comment]
The images in a custom deck are not stored on the server. You need to host
them somewhere else (imgur.com for example) and just supply the links to
the individual images.

**Comment by thorsten-panknin** [comment]
Okay,

so they're not explicitly cached or anything. Thanks.

**Comment by shanel** [comment]
Nope. Put in a custom set and deal out cards. Look at the source for the
page - images are getting pulled from where you linked to them.
