### ISSUE TITLE
Should be able to tick clock sections on existing clocks

### ISSUE THREAD

**Issue by Joey-the-noob** [shanel/roller#53]
Unable to tick clock sections once a clock is on the board.  If this feature exists, does not work on Safari 11 running in macOs 10.13 environment.

**Comment by shanel** [comment]
I assume you have double clicked or selected the Clock and hit reroll?

**Comment by Joey-the-noob** [comment]
Nope.  I had not tried that.  Beautiful!  Perhaps a tooltip to make it clear they work that way?

Thank you!  This code is overall FANTASTIC.

**Comment by shanel** [comment]
I *think* there is a tooltip mentioning it on the clock buttons or label?
