### ISSUE TITLE
Which branch is the app running?

### ISSUE THREAD

**Issue by aniketschneider** [shanel/roller#57]
`master` doesn't seem to be up-to-date with the live app, but the other branches look like feature branches.  If I wanted to fix a bug or open a PR for a new feature, what should I be branching off of?

**Comment by shanel** [comment]
Yeah, I have been pretty bad about merging back into master. The app is currently running new-dice. I'll try and merge back in

**Comment by shanel** [comment]
Did the merge. Master is up to date.
